//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autobuses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public int IIDASIENTO { get; set; }
        public Nullable<int> IIDVIAJE { get; set; }
        public Nullable<int> INDICEFILA { get; set; }
        public Nullable<int> INDICECOLUMNA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Viaje Viaje { get; set; }
    }
}
